### ISSUE TITLE
Test workflows

### ISSUE THREAD

**Issue by afgane** [CloudVE/galaxy-helm#39]
Pick a workflow and (try to) run through it. Fix the issues as you discover them.
- [x] [Galaxy 101](https://training.galaxyproject.org/training-material/topics/introduction/tutorials/galaxy-intro-101/tutorial.html) [Sergey]
- [x] [Sequence analysis mapping](https://training.galaxyproject.org/training-material/topics/sequence-analysis/tutorials/mapping/tutorial.html) [Enis]
- [x] [Microbial variant calling](https://training.galaxyproject.org/training-material/topics/variant-analysis/tutorials/microbial-variants/tutorial.html) [Nuwan]
- [ ] [Formation of the Super-Structures on the Inactive X](https://training.galaxyproject.org/training-material/topics/chip-seq/tutorials/formation_of_super-structures_on_xi/tutorial.html) [Alex]

Not scheduling jobs:
- [x] [De novo transcriptome reconstruction with RNA-Seq](https://galaxyproject.github.io/training-material/topics/transcriptomics/tutorials/de-novo/tutorial.html)

**Comment by afgane** [comment]
Comments from going through the [Sequence analysis mapping](https://training.galaxyproject.org/training-material/topics/sequence-analysis/tutorials/mapping/tutorial.html) tutorial:
- [x] FastQC jobs never end (#41)
- [x] Missing mm10 reference genome (along with many more; only a single `.loc` file seems to be loaded)
- [x] ~~MultiQC fails saying samtools is missing (https://github.com/galaxyproject/tools-iuc/issues/2448)~~
- [x] Whitelist tools with HTML output, ensuring proper file permissions (https://github.com/CloudVE/galaxy-kubernetes/commit/ff694139fe179f85922ffb7d4963ae5e40e599ca, https://github.com/CloudVE/galaxy-kubernetes/commit/ebe657107a36e890f156becfa1b57ecc1f3ac282)
- [x] ~~Running Bowtie2 produces an empty file and results in~~ This is due to the machine (4CPU, 16GB) being too small for the job; running on a larger machine (8CPUs, 32GB) works fine. Granted, this leaves better tool error reporting as a desire.
```
[E::hts_open_format] Failed to open file /galaxy/server/database/files/000/dataset_38.dat
samtools sort: failed to create "/galaxy/server/database/files/000/dataset_38.dat": Invalid argument
```

**Comment by nuwang** [comment]
Bacterial Variant Calling comments:

- [ ] Installing snippy from toolshed works, but the toolshed state is stuck at: “Installing Tool Dependencies”.
- [ ] changing the data type after upload results in an endless spinning wheel with “Metadata is being detected” or a message like “Try auto-detecting datatype or set it manually”
- [ ] Snippy generates an error

```
[09:21:51] This is snippy 4.3.6
[09:21:51] Written by Torsten Seemann
[09:21:51] Obtained from https://github.com/tseemann/snippy
[09:21:51] Detected operating system: linux
[09:21:51] Enabling bundled linux tools.
[09:21:51] Found bwa - /usr/local/bin/bwa
[09:21:51] Found bcftools - /usr/local/bin/bcftools
[09:21:51] Found samtools - /usr/local/bin/samtools
[09:21:51] Found java - /usr/local/bin/java
[09:21:51] Found snpEff - /usr/local/bin/snpEff
[09:21:51] Found samclip - /usr/local/bin/samclip
[09:21:51] Found seqtk - /usr/local/bin/seqtk
[09:21:51] Found parallel - /usr/local/bin/parallel
[09:21:51] Found freebayes - /usr/local/bin/freebayes
[09:21:51] Found freebayes-parallel - /usr/local/bin/freebayes-parallel
[09:21:51] Found fasta_generate_regions.py - /usr/local/bin/fasta_generate_regions.py
[09:21:51] Found vcfstreamsort - /usr/local/bin/vcfstreamsort
[09:21:51] Found vcfuniq - /usr/local/bin/vcfuniq
[09:21:51] Found vcffirstheader - /usr/local/bin/vcffirstheader
[09:21:51] Found gzip - /bin/gzip
[09:21:51] Found vt - /usr/local/bin/vt
[09:21:51] Found snippy-vcf_to_tab - /usr/local/bin/snippy-vcf_to_tab
[09:21:51] Found snippy-vcf_report - /usr/local/bin/snippy-vcf_report
[09:21:51] Checking version: samtools --version is >= 1.7 - ok, have 1.9
[09:21:51] Checking version: bcftools --version is >= 1.7 - ok, have 1.9
[09:21:51] Checking version: freebayes --version is >= 1.1 - ok, have 1.2
[09:21:51] Checking version: snpEff -version is >= 4.3 - ok, have 4.3
[09:21:51] Using reference: /galaxy/server/database/jobs_directory/000/11/working/ref.gbk
[09:21:51] Treating reference as 'genbank' format.
[09:21:51] Will use 1 CPU cores.
[09:21:51] Using read file: /galaxy/server/database/files/000/dataset_18.dat
[09:21:51] Using read file: /galaxy/server/database/files/000/dataset_30.dat
[09:21:51] Creating folder: out
[09:21:51] Changing working directory: out
[09:21:51] Creating reference folder: reference
[09:21:51] Extracting FASTA and GFF from reference.
[09:21:51] Wrote 1 sequences to ref.fa
[09:21:51] Wrote 171 features to ref.gff
[09:21:51] Creating reference/snpeff.config
[09:21:51] Freebayes will process 1 chunks of 200727 bp, 1 chunks at a time.
[09:21:51] Using BAM RG (Read Group) ID: out
[09:21:51] Running: samtools faidx reference/ref.fa 2>> snps.log
[09:21:51] Error running command, check out/snps.log
```

**Comment by almahmoud** [comment]
The most common error that came out of going through my tutorial is the fact that all the tools under the `deeptools` package don't work. The first problem a few days ago was that the job containers were using a galaxy image which didn't have the binaries for the tools in its path. That seems to be solved now, as mulled containers seem to be prepared for the job. However, that is not successfully happening. Specifically, one problem is that `curl` is not on the path, which impedes fetching `involucro`. I fixed that temporarily by exec-ing as root and installing `curl`, after which `involucro` started being successfully fetched. The error now seems to have to do with an inability to properly create the container, but I am not entirely sure:

```
galaxy.tools.deps.commands WARNING 2019-06-14 21:09:09,527 Passing program arguments as a string may be a security hazard if combined with untrusted input
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 599 0 599 0 0 4340 0 --:--:-- --:--:-- --:--:-- 4340
100 7922k 100 7922k 0 0 23.1M 0 --:--:-- --:--:-- --:--:-- 23.1M
/galaxy/server/database/involucro -v=3 -f /galaxy/server/lib/galaxy/tools/deps/mulled/invfile.lua -set CHANNELS='conda-forge,bioconda' -set TARGETS='deeptools=3.1.2,samtools=1.7' -set REPO='quay.io/local/mulled-v2-eb9e7907c7a753917c1e4d7a64384c047429618a:1abf1824431ec057c7d41be6f0c40e24843acde4-0' -set BINDS='build/dist:/usr/local/' -set TEST=true build-and-test
galaxy.tools.deps.commands WARNING 2019-06-14 21:09:09,935 Passing program arguments as a string may be a security hazard if combined with untrusted input
[Jun 14 21:09:09] ERRO Task processing failed: Docker not reachable: Get http://unix.sock/_ping: dial unix /var/run/docker.sock: connect: no such file or directory
galaxy.jobs.runners ERROR 2019-06-14 21:10:10,040 (2) Failure preparing job
Traceback (most recent call last):
File "/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 230, in prepare_job
stderr_file=stderr_file,
File "/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 260, in build_command_line
container = self._find_container(job_wrapper)
File "/galaxy/server/lib/galaxy/jobs/runners/__init__.py", line 428, in _find_container
job_info
File "/galaxy/server/lib/galaxy/tools/deps/containers.py", line 98, in find_container
container_description = self.find_best_container_description(enabled_container_types, tool_info)
File "/galaxy/server/lib/galaxy/tools/deps/containers.py", line 50, in find_best_container_description
container_description = self.container_registry.find_best_container_description(enabled_container_types, tool_info)
File "/galaxy/server/lib/galaxy/tools/deps/containers.py", line 229, in find_best_container_description
container_description = container_resolver.resolve(enabled_container_types, tool_info)
File "/galaxy/server/lib/galaxy/tools/deps/container_resolvers/mulled.py", line 458, in resolve
return docker_cached_container_description(targets, self.namespace, hash_func=self.hash_func, shell=self.shell)
File "/galaxy/server/lib/galaxy/tools/deps/container_resolvers/mulled.py", line 193, in docker_cached_container_description
cached_images = list_docker_cached_mulled_images(namespace, hash_func=hash_func)
File "/galaxy/server/lib/galaxy/tools/deps/container_resolvers/mulled.py", line 66, in list_docker_cached_mulled_images
images_and_versions = unicodify(subprocess.check_output(command)).strip().splitlines()
File "/usr/lib/python2.7/subprocess.py", line 216, in check_output
process = Popen(stdout=PIPE, *popenargs, **kwargs)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nuwang** [comment]
This appears to be a docker-in-docker issue. Since involucro needs to build the docker image, that naturally means we will need a running docker daemon. The first question I suppose is, can we not pre-build the image instead?

If we must do this, I think mapping in the parent's docker socket (i.e the one used by kubernetes) is highly undesirable.
This article has a good discussion on alternatives: https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25
We'll still need to run a privileged container, but mainly for building the containers. Of course, we'll have to run the built-container too, so I don't know who'll be in charge of that and clean up after it.

**Comment by nuwang** [comment]
With regard to the de-novo workflow: The issue is that the workflow execution manager doesn’t support db-skip-locked. Removing the db-skip-locked handler allows the workflow to execute. It looks like we'll have to have a dedicated handler with an alternative assignment method for processing workflows.

**Comment by nuwang** [comment]
The denovo workflow doesn't run because of the following issue
```
Error: Unable to access jarfile /trimmomatic.jar
readlink: invalid option -- 'e'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: readlink [-fnv] FILE

Display the value of a symlink

	-f	Canonicalize by following all symlinks
	-n	Don
```
The issue is clearly caused by busybox not supporting the -e flag. It looks like trimmomatic will need a new container with this issue fixed.

**Comment by natefoo** [comment]
> the workflow execution manager doesn’t support db-skip-locked

It should support it but it's not recommended because it means multiple workflows in the same history can be scheduled concurrently, jumbling up the datasets. I mentioned to @afgane just now:

> ￼￼￼￼￼nate 10:48
> It's supposed to handle this case and db-skip-locked is supported just not recommended (although fine in your case if you only have one handler) but anyway, keep the db-skip-locked job handler and use `workflow_schedulers_conf.xml` to set up a db-preassign or db-self workflow scheduler
